### ISSUE TITLE
How to get the asymptotic reference lines to show on the after I take of the facet grid

### ISSUE THREAD

**Issue by DorisAmoakohene** [DorisAmoakohene/Doris-Amoakohene-atime-for-asymptotic-Timings#10]
@tdhock

```
(best.list <- atime::references_best(atime.list))

p <- ggplot(best.list$measurements, aes(x = N, y = median, group = expr.name, colour = expr.name)) +
  geom_line() +
  geom_ribbon(aes(ymin = min, ymax = max, fill = expr.name), alpha = 0.5, colour = NA) +
  scale_x_log10("N = number of rows in the dataset", limits = c(1, 1e3), breaks = c(1, 10, 100, 1000)) +
  theme(
    text = element_text(size = 25),
    axis.text = element_text(size = 15),
    axis.title = element_text(size = 15)
  ) +
  scale_y_log10("Computational Time (Seconds)") +
  labs(x = "N = number of rows in the dataset", y = "Computational Time (Seconds)") +
  theme(legend.position = "none")

p <- p + geom_dl(aes(label = gsub(".replacement", "", expr.name)), method = list(dl.combine("last.points"), cex = 1.2))

ggsave("best.list.png", plot = p, width = 10, height = 5, unit = "in", dpi = 300)

```
![best list](https://github.com/user-attachments/assets/c09a3dee-08dc-496e-89da-d93e23da83ca)

How to get the purple lines to show on the plot, to show the various asymptotic reference lines.

```

tried to get it from here 
https://github.com/tdhock/atime/blob/main/R/references.R#L115

but doesnt seem to work 

```

**Comment by tdhock** [comment]
that's the right place to look in the code
do you need custom code though?
why not just use the plot method, but edit the data in measurements? (subset only time not memory)

**Comment by DorisAmoakohene** [comment]
As discussed I am trying to plot the three graph(atime.list, best.list, pred.list)

**Comment by DorisAmoakohene** [comment]
@tdhock 
atime.list

![atime list](https://github.com/user-attachments/assets/23cb37f2-37c9-453d-8d89-2d68b30efc58)

best.list

![best list](https://github.com/user-attachments/assets/dec52308-c24a-440d-9c64-248b6948243f)

pred.list

![pred list](https://github.com/user-attachments/assets/2a4c244a-f035-4c15-8987-e438571d1012)


I am trying to plot the three graph(atime.list, best.list, pred.list)

```
> subject.size.vec <- unique(as.integer(10^seq(0,2,l=100)))
> atime.list <- atime::atime(
+   N=subject.size.vec,
+   setup={
+     subject <- paste(rep("a", N), collapse="")
+     pattern <- paste(rep(c("a?", "a"), each=N), collapse="")
+   },
+   times=10,
+   seconds.limit=0.1,
+   PCRE = regexpr(pattern, subject, perl=TRUE),
+   TRE = regexpr(pattern, subject, perl=FALSE)
+   )
> d <- ggplot(atime.list$measurements, aes(x = N, y = median, group = expr.name, colour = expr.name)) +
+   geom_line() +
+   geom_ribbon(aes(ymin = min, ymax = max, fill = expr.name), alpha = 0.5, colour = NA) +
+   scale_x_log10("N = number of rows in the dataset", limits = c(1, 1e3), breaks = 10^seq(1, 3)) +
+   scale_y_log10("Computational Time (Seconds)") +
+   labs(x = "N = number of rows in the dataset", y = "Computational Time (Seconds)") +
+   theme(legend.position = "none")
> 
> d <- d + geom_dl(aes(label = gsub(".replacement", "", expr.name)), method = list(dl.combine("last.points"), cex = 1.2))
> 
> ggsave("atime.list.png", plot = d, width = 5, height = 3, unit = "in", dpi = 300)
> (best.list <- atime::references_best(atime.list))
references_best list with 150 measurements, best fit complexity:
PCRE (2^N seconds)
TRE (N^3 seconds)
> 
> p <- ggplot(best.list$measurements, aes(x = N, y = median, group = expr.name, colour = expr.name)) +
+   geom_line() +
+   geom_ribbon(aes(ymin = min, ymax = max, fill = expr.name), alpha = 0.5, colour = NA) +
+   scale_x_log10("N = number of rows in the dataset", limits = c(1, 1e3), breaks = c(1, 10, 100, 1000)) +
+   scale_y_log10("Computational Time (Seconds)") +
+   labs(x = "N = number of rows in the dataset", y = "Computational Time (Seconds)") +
+   theme(legend.position = "none")
> 
> p <- p + geom_dl(aes(label = gsub(".replacement", "", expr.name)), method = list(dl.combine("last.points"), cex = 1.2))
> 
> ggsave("best.list.png", plot = p, width = 5, height = 3, unit = "in", dpi = 300)

> pred.list <- predict(best.list, seconds=1e-2 )
> y <- ggplot(pred.list$measurements, aes(x = N, y = median, group = expr.name, colour = expr.name)) +
+   geom_line() +
+   geom_ribbon(aes(ymin = min, ymax = max, fill = expr.name), alpha = 0.5, colour = NA) +
+   scale_x_log10("N = number of rows in the dataset", limits = c(1, 1e3), breaks = c(1, 10, 100, 1000)) +
+   scale_y_log10("Computational Time (Seconds)") +
+   labs(x = "N = number of rows in the dataset", y = "Computational Time (Seconds)") +
+   theme(legend.position = "none")
> 
> y <- y + geom_dl(aes(label = gsub(".replacement", "", expr.name)), method = list(dl.combine("last.points"), cex = 1.2))
> 
> ggsave("pred.list.png", plot = p, width = 5, height = 3, unit = "in", dpi = 300)

```

all the plot look the same, How do I plot the asymptotic timing in my custom plot and how do I plot pred.list too showing the N and seconds limit.

**Comment by DorisAmoakohene** [comment]
again if I use what you showed me this morning, the best.list looks weird

atime.list
![atime_plot](https://github.com/user-attachments/assets/ca464249-077f-4b6d-a3c5-b16d0478acc3)

best.list
![best_plot](https://github.com/user-attachments/assets/a0d96d1e-7432-4665-a00d-6bddaf6ba037)

pred.list
![pred_plot](https://github.com/user-attachments/assets/d9197064-6435-4b0b-9768-097efeba814c)

this is the code I am using

```
subject.size.vec <- unique(as.integer(10^seq(0,2,l=100)))
> atime.list <- atime::atime(
+   N=subject.size.vec,
+   setup={
+     subject <- paste(rep("a", N), collapse="")
+     pattern <- paste(rep(c("a?", "a"), each=N), collapse="")
+   },
+   times=10,
+   seconds.limit=0.1,
+   PCRE = regexpr(pattern, subject, perl=TRUE),
+   TRE = regexpr(pattern, subject, perl=FALSE)
+   )

> 
> atime.list$measurements$kilobytes = NA
> 
> png("atime_plot.png", width = 800, height = 600)
> 
> plot(atime.list)+ 
+   scale_y_log10("Computation Time (seconds)")+
+   facet_null()

> 
> 
> dev.off()
null device 
          1 
> best.list$measurements$kilobytes = NA
> 
> png("best_plot.png", width = 800, height = 600)
> 
> plot(best.list)+ 
+   scale_y_log10("Computation Time (seconds)")+
+   facet_null()

> 
> dev.off()
null device 
          1 
> pred.list$measurements$kilobytes = NA
> 
> 
> png("pred_plot.png", width = 800, height = 600)
> plot(pred.list)+ 
+   scale_y_log10("Computation Time (seconds)")+
+   facet_null()

> 
> dev.off()
null device 
          1 

```

**Comment by tdhock** [comment]
best.list$measurements is a data table
you should try to subset it before plotting.
did you try something like this?
```r
best.list$measurements = best.list$measurements[unit == "seconds"]
plot(best.list)
```

**Comment by DorisAmoakohene** [comment]
I just did and I getting this result 

```
> best.list$measurements = best.list$measurements[unit == "seconds"]
> 
> png("best2plot.png", width = 800, height = 600)
> plot(best.list)+ 
+   scale_y_log10("Computation Time (seconds)")+
+   facet_null()
Scale for y is already present.
Adding another scale for y, which will replace the existing scale.
> dev.off()
null device 
          1 

```

![best2plot](https://github.com/user-attachments/assets/524564e4-a067-4a5c-84e6-16a57cdda832)

**Comment by tdhock** [comment]
for this plot you should use facet_grid (delete facet_null)

**Comment by DorisAmoakohene** [comment]
This is the plot I have made for atime.list 
![atime_plot](https://github.com/user-attachments/assets/7a8bde72-e6ec-4fd5-b0ce-3b22538d3686)

I have this  plot for best.list

![best2plot](https://github.com/user-attachments/assets/9a815943-d1e8-417f-a9b3-9560f2b0a2eb)

**Comment by DorisAmoakohene** [comment]
@tdhock these are the final plot for atime.list and best.list
let me know what you think

atime.list

![atime list plot](https://github.com/user-attachments/assets/d2822f65-f29a-42bc-a35a-ced6d7a63327)

best.list

![best list plot](https://github.com/user-attachments/assets/1a0a801a-c54d-4c7b-990f-7e5db4ee8c0b)

**Comment by DorisAmoakohene** [comment]
I am still figuring out how to run pred.list with the 

```
pred.list <- predict(best.list, seconds=1e-2 , kilobytes=10)

```

**Comment by tdhock** [comment]
these figures look good

I don't understand your issue about predict, can you please clarify with a minimal reproducible example, code + data + outputs.

**Comment by DorisAmoakohene** [comment]
```
pred.list <- predict(best.list, seconds=1e-2 ) #, kilobytes=10)

pred.list$measurements$kilobytes = NA

f = plot(pred.list)+ 
  scale_y_log10("Computation Time (seconds)")+
  facet_null()
ggsave("pred.list.plot.png", plot = f, width = 5, height = 3, unit = "in", dpi = 300)
```

the TRE cut at some point and I am not able to run with the kilobyte, like this 
```
pred.list <- predict(best.list, seconds=1e-2, kilobytes=10)
```
![pred list plot](https://github.com/user-attachments/assets/7029d38b-fa37-4d73-a329-bfee94100beb)

**Comment by tdhock** [comment]
I don't see a question. When you want help, and/or a response, can you please write a question, with a question mark at the end?

are you trying to display N= label for TRE? 
you wrote `seconds=1e-2` and I see that there is no data for TRE that intersects 1e-2=0.01 seconds, so there is no label drawn.
You could try decreasing `seconds=1e-3` or increasing N

**Comment by DorisAmoakohene** [comment]
![pred list plot](https://github.com/user-attachments/assets/f48f0652-36d5-4b1d-9c18-a7362116c6fe)

Thanks @tdhock, I figure that out already.

Above is the results 
let me know what you think about the figure?

**Comment by tdhock** [comment]
it is ok but it would be better if N went up to 100 on the X axis. please use `scale_x_log10`

**Comment by DorisAmoakohene** [comment]
![pred list plot](https://github.com/user-attachments/assets/6495ecbe-2f64-4b71-b627-7e1235320312)

good?

**Comment by DorisAmoakohene** [comment]
![pred list plot](https://github.com/user-attachments/assets/51aa4014-245d-4fb2-a7dd-29482bcae19d)

good?

**Comment by tdhock** [comment]
please change X axis from "column" to "columns"

**Comment by DorisAmoakohene** [comment]
Alright, done 
![pred list plot](https://github.com/user-attachments/assets/e8d8b9f4-7cd5-4fba-b594-d3a490c35302)

**Comment by tdhock** [comment]
it may be more convincing to show larger N / seconds.limit=0.1 or similar
but this is good for a quick/simple example
