### ISSUE TITLE
A few things to revise

### ISSUE THREAD

**Issue by Anirban166** [DorisAmoakohene/Doris-Amoakohene-atime-for-asymptotic-Timings#8]
- Please try to write something different for lines which are repetitive. For example, in the part where you talk about performance tests, I see:

https://github.com/DorisAmoakohene/Doris-Amoakohene-atime-for-asymptotic-Timings/blob/ebff273af9c402d0352bd3865138826e7152d5f6/DorisAmoakohene.tex#L373

'It helps in understanding the impact of the regression and the effectiveness of the fix.'

https://github.com/DorisAmoakohene/Doris-Amoakohene-atime-for-asymptotic-Timings/blob/ebff273af9c402d0352bd3865138826e7152d5f6/DorisAmoakohene.tex#L382

'The output captures the computational time for each version of the \texttt{data.table} package across different dataset sizes, providing a comprehensive understanding of the impact of the regression and the effectiveness of the new version.'

https://github.com/DorisAmoakohene/Doris-Amoakohene-atime-for-asymptotic-Timings/blob/ebff273af9c402d0352bd3865138826e7152d5f6/DorisAmoakohene.tex#L406

'It will compare the performance of these versions, highlighting the impact of the regression and the effectiveness of the fix.'

(In these three cases above, 'impact of the regression and the effectiveness of the' is repeated for example)

**Comment by Anirban166** [comment]
https://github.com/DorisAmoakohene/Doris-Amoakohene-atime-for-asymptotic-Timings/blob/ebff273af9c402d0352bd3865138826e7152d5f6/DorisAmoakohene.tex#L494

Then in here, it says 'Furthermore, we discussed the design choice to keep separate functions for comparative benchmarking and performance testing ... ' but it's not discussed above and only below after that line/paragraph (After placing it accordingly or changing to something like 'we will be discussing ... ', I would suggest you to place it in a more appropriate section above as this seems to be a design decision thing)

**Comment by Anirban166** [comment]
https://github.com/DorisAmoakohene/Doris-Amoakohene-atime-for-asymptotic-Timings/blob/ebff273af9c402d0352bd3865138826e7152d5f6/DorisAmoakohene.tex#L494

Then in here, it says 'Furthermore, we discussed the design choice to keep separate functions for comparative benchmarking and performance testing ... ' but it's not discussed above and only below after that line/paragraph 

(And after you organize it accordingly or change the narrative to something like 'we will be discussing ... ', I would suggest you to place it in a more appropriate section above as this seems to be a design decision thing)

**Comment by Anirban166** [comment]
https://github.com/DorisAmoakohene/Doris-Amoakohene-atime-for-asymptotic-Timings/blob/ebff273af9c402d0352bd3865138826e7152d5f6/DorisAmoakohene.tex#L494

- Then in here, it says 'Furthermore, we discussed the design choice to keep separate functions for comparative benchmarking and performance testing ... ' but it's not discussed above and only below after that line/paragraph 

(And after you organize it accordingly or change the narrative to something like 'we will be discussing ... ', I would suggest you to place it in a more appropriate section above as this seems to be a design decision thing)

**Comment by Anirban166** [comment]
https://github.com/DorisAmoakohene/Doris-Amoakohene-atime-for-asymptotic-Timings/blob/ebff273af9c402d0352bd3865138826e7152d5f6/DorisAmoakohene.tex#L405

- This still hasn't been revised so please correct what you wanted to convey in 'almost as the first simple'

**Comment by Anirban166** [comment]
https://github.com/DorisAmoakohene/Doris-Amoakohene-atime-for-asymptotic-Timings/blob/ebff273af9c402d0352bd3865138826e7152d5f6/DorisAmoakohene.tex#L169

- Then again, this part here

**Comment by Anirban166** [comment]
https://github.com/DorisAmoakohene/Doris-Amoakohene-atime-for-asymptotic-Timings/blob/ebff273af9c402d0352bd3865138826e7152d5f6/DorisAmoakohene.tex#L424
- Also please make it 'GitHub Actions' here (or capitalize A, H, and G - these terms are proper nouns) 

(I'm not sure why your edits converted all instances of 'GitHub' to 'github' but I fixed the rest in #7)

**Comment by DorisAmoakohene** [comment]
fixed this

> https://github.com/DorisAmoakohene/Doris-Amoakohene-atime-for-asymptotic-Timings/blob/ebff273af9c402d0352bd3865138826e7152d5f6/DorisAmoakohene.tex#L424
> 
> * Also please make it 'GitHub Actions' here (or capitalize A, H, and G - these terms are proper nouns)
> 
> (I'm not sure why your edits converted all instances of 'GitHub' to 'github' but I fixed the rest in #7)

I have fixed this
